### ISSUE TITLE
Hash passwords

### ISSUE THREAD

**Issue by MayD524** [MayD524/TechHowlerSite#5]
Yes passwords need to be hashed, and yes they currently are not due to them making development time much slower, before release please either me or someone (please assign yourself if you want it) add in hashed passwords.

Make sure to use salt too!

**Comment by lodenrogue** [comment]
Is this the only file you'll need to call the hashing method from?

authBase.ts line 75

**Comment by MayD524** [comment]
So the hashing method would probably be done in server/src/dbhandler.py or something like that, just so all the routes can use it.

Sorry for lack of documentation I haven't gotten around to it

**Comment by lodenrogue** [comment]
You should put the hashing logic in it's own class so that it can evolve independently of the rest of your dbHandler stuff. You can call this class from your dbHandler.

**Comment by MayD524** [comment]
thats fair, if you want to implement you're more than welcome to! Just it has to be on the python side of things to make life easier.

**Comment by lodenrogue** [comment]
Yes. I'll add a class that hashes and salts an input text. You can integrate it after

**Comment by MayD524** [comment]
Thank you!

**Comment by lodenrogue** [comment]
PR: https://github.com/MayD524/TechHowlerSite/pull/6

**Comment by MayD524** [comment]
👍 looks good

**Comment by lodenrogue** [comment]
Thanks
