### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by lodenrogue** [MayD524/TechHowlerSite#8]
Can we add some info in the README on how to build and run the application? I'd like to help with some of the other issues but I want to get the app running first.

**Comment by MayD524** [comment]
Sorry for the long delay, I've been busy with other things. If you want I can add a readme to the project. Or I might make  build script

**Comment by lodenrogue** [comment]
Either is fine but I think the README would be good for people who want a better understanding of the project and building it themselves.

**Comment by MayD524** [comment]
I mean I don't expect more than 10 people to use this app, it's for my school so I think just how to build should be enough for now

**Comment by lodenrogue** [comment]
Sounds good to me

**Comment by MayD524** [comment]
updated!
